In [2]:
import pandas as pd

In [3]:
#Series (Single Column)
cgpa = pd.Series([8.2,7.4,9.1])
cgpa

0    8.2
1    7.4
2    9.1
dtype: float64

In [4]:
#DataFrame (Multiple Columns)
df = pd.DataFrame({
    "Name" : ["Alice", "Bob", "John"],
    "CGPA" : [8.2, 7.4, 9.1],
    "Package" : [12, 8, 18]
})

In [5]:
df

    Name  CGPA  Package
0  Alice   8.2       12
1    Bob   7.4        8
2   John   9.1       18

In [6]:
df["CGPA"]

0    8.2
1    7.4
2    9.1
Name: CGPA, dtype: float64

In [7]:
df[df["CGPA"] > 8]

    Name  CGPA  Package
0  Alice   8.2       12
2   John   9.1       18

In [8]:
students = pd.Series(
    [8.9, 7.5, 9.1],
    index=["Alice", "Bob", "Charlie"]
)

df

    Name  CGPA  Package
0  Alice   8.2       12
1    Bob   7.4        8
2   John   9.1       18

In [9]:
students["Bob"]

np.float64(7.5)

In [10]:
#Reading and Inspecting Data
df = pd.read_csv("/kaggle/input/datasets/somya2115/placement-csv/placement.csv")

In [11]:
df

    Unnamed: 0  cgpa     iq  placement
0            0   6.8  123.0          1
1            1   5.9  106.0          0
2            2   5.3  121.0          0
3            3   7.4  132.0          1
4            4   5.8  142.0          0
..         ...   ...    ...        ...
95          95   4.3  200.0          0
96          96   4.4   42.0          0
97          97   6.7  182.0          1
98          98   6.3  103.0          1
99          99   6.2  113.0          1

[100 rows x 4 columns]

In [12]:
df.head()

   Unnamed: 0  cgpa     iq  placement
0           0   6.8  123.0          1
1           1   5.9  106.0          0
2           2   5.3  121.0          0
3           3   7.4  132.0          1
4           4   5.8  142.0          0

In [13]:
df.head(10)

   Unnamed: 0  cgpa     iq  placement
0           0   6.8  123.0          1
1           1   5.9  106.0          0
2           2   5.3  121.0          0
3           3   7.4  132.0          1
4           4   5.8  142.0          0
5           5   7.1   48.0          1
6           6   5.7  143.0          0
7           7   5.0   63.0          0
8           8   6.1  156.0          0
9           9   5.1   66.0          0

In [14]:
df.tail()

    Unnamed: 0  cgpa     iq  placement
95          95   4.3  200.0          0
96          96   4.4   42.0          0
97          97   6.7  182.0          1
98          98   6.3  103.0          1
99          99   6.2  113.0          1

In [15]:
df.sample(5) #Random data

    Unnamed: 0  cgpa     iq  placement
9            9   5.1   66.0          0
64          64   7.0   64.0          1
5            5   7.1   48.0          1
58          58   8.0   79.0          1
72          72   7.3  116.0          1

In [16]:
df.shape

(100, 4)

In [17]:
df.columns

Index(['Unnamed: 0', 'cgpa', 'iq', 'placement'], dtype='object')

In [18]:
df.dtypes

Unnamed: 0      int64
cgpa          float64
iq            float64
placement       int64
dtype: object

In [19]:
df.info() #Very used

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  100 non-null    int64
 1   cgpa        100 non-null    float64
 2   iq          100 non-null    float64
 3   placement   100 non-null    int64
dtypes: float64(2), int64(2)
memory usage: 3.3 KB

In [20]:
df.describe()

       Unnamed: 0        cgpa          iq   placement
count  100.000000  100.000000  100.000000  100.000000
mean    49.500000    5.991000  123.580000    0.500000
std     29.011492    1.143634   39.944198    0.502519
min      0.000000    3.300000   37.000000    0.000000
25%     24.750000    5.075000  101.500000    0.000000
50%     49.500000    6.000000  127.500000    0.500000
75%     74.250000    6.900000  149.000000    1.000000
max     99.000000    8.500000  233.000000    1.000000

In [21]:
df.isnull().sum() #By this, missing datas can be identified

Unnamed: 0    0
cgpa          0
iq            0
placement     0
dtype: int64

In [22]:
# ==========================================
# Dataset Inspection Checklist
# ==========================================

# Display the first 5 rows of the dataset
# df.head()

# Display the last 5 rows of the dataset
# df.tail()

# Display 5 random rows from the dataset
# df.sample(5)

# Display the shape of the dataset
# Output: (number_of_rows, number_of_columns)
# df.shape

# Display all column names
# df.columns

# Display the data type of each column
# df.dtypes

# Display complete dataset information
# Includes:
# - Number of rows
# - Number of columns
# - Non-null values
# - Data types
# - Memory usage
# df.info()

# Display statistical summary of numerical columns
# Includes:
# - Count
# - Mean
# - Standard Deviation
# - Minimum
# - 25th Percentile
# - Median (50%)
# - 75th Percentile
# - Maximum
# df.describe()

# Display the total number of missing (NaN) values in each column
# df.isnull().sum()

# Display the total number of duplicate rows
# df.duplicated().sum()

# ==========================================
# Categorical Column Inspection
# (Replace "column_name" with an actual column)
# ==========================================

# Display all unique values in a column
# Example:
# df["gender"].unique()

# Display the total number of unique values
# Example:
# df["gender"].nunique()

# Display the frequency of each unique value
# Example:
# Male      120
# Female     80
# df["column_name"].value_counts()

In [23]:
#Selecting Data (COLUMNS)

In [24]:
df["cgpa"]

0     6.8
1     5.9
2     5.3
3     7.4
4     5.8
     ...
95    4.3
96    4.4
97    6.7
98    6.3
99    6.2
Name: cgpa, Length: 100, dtype: float64

In [25]:
df

    Unnamed: 0  cgpa     iq  placement
0            0   6.8  123.0          1
1            1   5.9  106.0          0
2            2   5.3  121.0          0
3            3   7.4  132.0          1
4            4   5.8  142.0          0
..         ...   ...    ...        ...
95          95   4.3  200.0          0
96          96   4.4   42.0          0
97          97   6.7  182.0          1
98          98   6.3  103.0          1
99          99   6.2  113.0          1

[100 rows x 4 columns]

In [26]:
df[["cgpa", "iq"]]

    cgpa     iq
0    6.8  123.0
1    5.9  106.0
2    5.3  121.0
3    7.4  132.0
4    5.8  142.0
..   ...    ...
95   4.3  200.0
96   4.4   42.0
97   6.7  182.0
98   6.3  103.0
99   6.2  113.0

[100 rows x 2 columns]

In [27]:
#Selecting Data (ROWS)

In [28]:
df.iloc[0] #iloc = Integer Location

Unnamed: 0      0.0
cgpa            6.8
iq            123.0
placement       1.0
Name: 0, dtype: float64

In [29]:
df.iloc[1]

Unnamed: 0      1.0
cgpa            5.9
iq            106.0
placement       0.0
Name: 1, dtype: float64

In [30]:
df.iloc[:3] #First 3 Rows

   Unnamed: 0  cgpa     iq  placement
0           0   6.8  123.0          1
1           1   5.9  106.0          0
2           2   5.3  121.0          0

In [31]:
#Selecting Rows and Columns

In [32]:
df.iloc[:3, 1] #First 3 rows only CGPA

0    6.8
1    5.9
2    5.3
Name: cgpa, dtype: float64

In [33]:
df.iloc[:5,[1,2]] #First 5 rows, CGPA and IQ

   cgpa     iq
0   6.8  123.0
1   5.9  106.0
2   5.3  121.0
3   7.4  132.0
4   5.8  142.0

In [34]:
#Boolean Indexing

In [35]:
df[df["cgpa"] > 8]

    Unnamed: 0  cgpa     iq  placement
37          37   8.1  149.0          1
53          53   8.3  168.0          1
65          65   8.1  166.0          1
69          69   8.5  120.0          1

In [36]:
df[
(df["cgpa"] > 8) & (df["iq"] > 150)
]

    Unnamed: 0  cgpa     iq  placement
53          53   8.3  168.0          1
65          65   8.1  166.0          1

In [37]:
#Sorting

In [38]:
df.sort_values("cgpa")

    Unnamed: 0  cgpa     iq  placement
17          17   3.3  183.0          0
50          50   3.5  233.0          0
31          31   3.9  109.0          0
18          18   4.0  100.0          0
68          68   4.0   75.0          0
..         ...   ...    ...        ...
58          58   8.0   79.0          1
65          65   8.1  166.0          1
37          37   8.1  149.0          1
53          53   8.3  168.0          1
69          69   8.5  120.0          1

[100 rows x 4 columns]

In [39]:
df.sort_values("cgpa", ascending=False)

    Unnamed: 0  cgpa     iq  placement
69          69   8.5  120.0          1
53          53   8.3  168.0          1
37          37   8.1  149.0          1
65          65   8.1  166.0          1
58          58   8.0   79.0          1
..         ...   ...    ...        ...
18          18   4.0  100.0          0
68          68   4.0   75.0          0
31          31   3.9  109.0          0
50          50   3.5  233.0          0
17          17   3.3  183.0          0

[100 rows x 4 columns]

In [40]:
#Unique Values

In [41]:
df["cgpa"].unique()

array([6.8, 5.9, 5.3, 7.4, 5.8, 7.1, 5.7, 5. , 6.1, 5.1, 6. , 6.9, 5.4,
       6.4, 5.2, 3.3, 4. , 6.6, 4.9, 4.7, 7. , 7.6, 3.9, 4.8, 8.1, 6.5,
       4.6, 7.5, 3.5, 8.3, 7.8, 8. , 7.3, 6.3, 8.5, 6.7, 4.4, 4.3, 6.2])

In [42]:
df["cgpa"].nunique() #Total number of UNIQUE

39

In [43]:
df["cgpa"].value_counts()

cgpa
4.9    6
6.1    5
5.2    5
6.0    5
7.0    5
5.7    4
6.8    4
7.3    4
5.4    4
6.5    4
4.8    4
7.5    3
4.7    3
5.1    3
6.3    3
5.0    3
6.9    3
4.0    2
7.1    2
5.3    2
4.4    2
5.8    2
6.4    2
6.7    2
8.1    2
6.6    2
7.6    2
7.4    1
5.9    1
3.9    1
3.3    1
7.8    1
8.3    1
3.5    1
4.6    1
8.5    1
8.0    1
4.3    1
6.2    1
Name: count, dtype: int64

In [44]:
df[["cgpa"]] #DataFrame

    cgpa
0    6.8
1    5.9
2    5.3
3    7.4
4    5.8
..   ...
95   4.3
96   4.4
97   6.7
98   6.3
99   6.2

[100 rows x 1 columns]

In [45]:
df["cgpa"] #Series

0     6.8
1     5.9
2     5.3
3     7.4
4     5.8
     ...
95    4.3
96    4.4
97    6.7
98    6.3
99    6.2
Name: cgpa, Length: 100, dtype: float64

In [46]:
#Data Cleaning

In [47]:
df.isnull().sum()

Unnamed: 0    0
cgpa          0
iq            0
placement     0
dtype: int64

In [48]:
df.dropna() #Removes rows that have missing values

    Unnamed: 0  cgpa     iq  placement
0            0   6.8  123.0          1
1            1   5.9  106.0          0
2            2   5.3  121.0          0
3            3   7.4  132.0          1
4            4   5.8  142.0          0
..         ...   ...    ...        ...
95          95   4.3  200.0          0
96          96   4.4   42.0          0
97          97   6.7  182.0          1
98          98   6.3  103.0          1
99          99   6.2  113.0          1

[100 rows x 4 columns]

In [49]:
df.fillna(0) #Fill with 0's

    Unnamed: 0  cgpa     iq  placement
0            0   6.8  123.0          1
1            1   5.9  106.0          0
2            2   5.3  121.0          0
3            3   7.4  132.0          1
4            4   5.8  142.0          0
..         ...   ...    ...        ...
95          95   4.3  200.0          0
96          96   4.4   42.0          0
97          97   6.7  182.0          1
98          98   6.3  103.0          1
99          99   6.2  113.0          1

[100 rows x 4 columns]

In [50]:
#Fill with the Mean

In [51]:
df["cgpa"] = df["cgpa"].fillna(df["cgpa"].mean())

In [52]:
#Fill with the Most Frequent Value

In [53]:
df["cgpa"] = df["cgpa"].fillna(df["cgpa"].mode()[0])

In [54]:
#Duplicated Rows

In [55]:
df.duplicated()

0     False
1     False
2     False
3     False
4     False
      ...
95    False
96    False
97    False
98    False
99    False
Length: 100, dtype: bool

In [56]:
df.duplicated().sum()

np.int64(0)

In [57]:
df.drop_duplicates()

    Unnamed: 0  cgpa     iq  placement
0            0   6.8  123.0          1
1            1   5.9  106.0          0
2            2   5.3  121.0          0
3            3   7.4  132.0          1
4            4   5.8  142.0          0
..         ...   ...    ...        ...
95          95   4.3  200.0          0
96          96   4.4   42.0          0
97          97   6.7  182.0          1
98          98   6.3  103.0          1
99          99   6.2  113.0          1

[100 rows x 4 columns]

In [58]:
#Changing Data Type

In [59]:
df["cgpa"] = df["cgpa"].astype(int)

In [60]:
#Data Transformation and Feature Engineering

In [62]:
performance_df = pd.read_csv("/kaggle/input/datasets/devansodariya/student-performance-data/student_data.csv")

In [63]:
performance_df

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,famrel,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3
0,GP,F,18,U,GT3,A,4,4,at_home,teacher,...,4,3,4,1,1,3,6,5,6,6
1,GP,F,17,U,GT3,T,1,1,at_home,other,...,5,3,3,1,1,3,4,5,5,6
2,GP,F,15,U,LE3,T,1,1,at_home,other,...,4,3,2,2,3,3,10,7,8,10
3,GP,F,15,U,GT3,T,4,2,health,services,...,3,2,2,1,1,5,2,15,14,15
4,GP,F,16,U,GT3,T,3,3,other,other,...,4,3,2,1,2,5,4,6,10,10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
390,MS,M,20,U,LE3,A,2,2,services,services,...,5,5,4,4,5,4,11,9,9,9
391,MS,M,17,U,LE3,T,3,1,services,services,...,2,4,5,3,4,2,3,14,16,16
392,MS,M,21,R,GT3,T,1,1,other,other,...,5,5,3,3,3,3,3,10,8,7
393,MS,M,18,R,LE3,T,3,2,services,other,...,4,4,1,3,4,5,0,11,12,10
394,MS,M,19,U,LE3,T,1,1,other,at_home,...,3,2,3,3,3,5,5,8,9,9

In [69]:
df2 = performance_df

df2[["age"]]

     age
0     18
1     17
2     15
3     15
4     16
..   ...
390   20
391   17
392   21
393   18
394   19

[395 rows x 1 columns]

In [70]:
#Age after 5 years

df2[["Age after 5 years"]] = df2["age"] + 5

In [72]:
df2[["Age after 5 years"]] #Feature Engineering

     Age after 5 years
0                   23
1                   22
2                   20
3                   20
4                   21
..                 ...
390                 25
391                 22
392                 26
393                 23
394                 24

[395 rows x 1 columns]

In [73]:
df2[["age", "Age after 5 years"]]

     age  Age after 5 years
0     18                 23
1     17                 22
2     15                 20
3     15                 20
4     16                 21
..   ...                ...
390   20                 25
391   17                 22
392   21                 26
393   18                 23
394   19                 24

[395 rows x 2 columns]

In [74]:
df2

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3,Age after 5 years
0,GP,F,18,U,GT3,A,4,4,at_home,teacher,...,3,4,1,1,3,6,5,6,6,23
1,GP,F,17,U,GT3,T,1,1,at_home,other,...,3,3,1,1,3,4,5,5,6,22
2,GP,F,15,U,LE3,T,1,1,at_home,other,...,3,2,2,3,3,10,7,8,10,20
3,GP,F,15,U,GT3,T,4,2,health,services,...,2,2,1,1,5,2,15,14,15,20
4,GP,F,16,U,GT3,T,3,3,other,other,...,3,2,1,2,5,4,6,10,10,21
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
390,MS,M,20,U,LE3,A,2,2,services,services,...,5,4,4,5,4,11,9,9,9,25
391,MS,M,17,U,LE3,T,3,1,services,services,...,4,5,3,4,2,3,14,16,16,22
392,MS,M,21,R,GT3,T,1,1,other,other,...,5,3,3,3,3,3,10,8,7,26
393,MS,M,18,R,LE3,T,3,2,services,other,...,4,1,3,4,5,0,11,12,10,23
394,MS,M,19,U,LE3,T,1,1,other,at_home,...,2,3,3,3,5,5,8,9,9,24

In [75]:
df

    Unnamed: 0  cgpa     iq  placement
0            0     6  123.0          1
1            1     5  106.0          0
2            2     5  121.0          0
3            3     7  132.0          1
4            4     5  142.0          0
..         ...   ...    ...        ...
95          95     4  200.0          0
96          96     4   42.0          0
97          97     6  182.0          1
98          98     6  103.0          1
99          99     6  113.0          1

[100 rows x 4 columns]

In [ ]:
#Arithmetic Operations

In [76]:
df["iq"] = df["iq"] * 1.10
df[["iq"]]

       iq
0   135.3
1   116.6
2   133.1
3   145.2
4   156.2
..    ...
95  220.0
96   46.2
97  200.2
98  113.3
99  124.3

[100 rows x 1 columns]

In [ ]:
#apply()

In [78]:
def grade(cgpa):
    if cgpa >= 8:
        return "Excellent"
    elif cgpa >= 7:
        return "Good"
    else:
        return "Average"

df["Performance"] = df["cgpa"].apply(grade)

In [80]:
df[["cgpa","Performance"]]

    cgpa Performance
0      6     Average
1      5     Average
2      5     Average
3      7        Good
4      5     Average
..   ...         ...
95     4     Average
96     4     Average
97     6     Average
98     6     Average
99     6     Average

[100 rows x 2 columns]

In [83]:
#where

df2

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3,Age after 5 years
0,GP,F,18,U,GT3,A,4,4,at_home,teacher,...,3,4,1,1,3,6,5,6,6,23
1,GP,F,17,U,GT3,T,1,1,at_home,other,...,3,3,1,1,3,4,5,5,6,22
2,GP,F,15,U,LE3,T,1,1,at_home,other,...,3,2,2,3,3,10,7,8,10,20
3,GP,F,15,U,GT3,T,4,2,health,services,...,2,2,1,1,5,2,15,14,15,20
4,GP,F,16,U,GT3,T,3,3,other,other,...,3,2,1,2,5,4,6,10,10,21
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
390,MS,M,20,U,LE3,A,2,2,services,services,...,5,4,4,5,4,11,9,9,9,25
391,MS,M,17,U,LE3,T,3,1,services,services,...,4,5,3,4,2,3,14,16,16,22
392,MS,M,21,R,GT3,T,1,1,other,other,...,5,3,3,3,3,3,10,8,7,26
393,MS,M,18,R,LE3,T,3,2,services,other,...,4,1,3,4,5,0,11,12,10,23
394,MS,M,19,U,LE3,T,1,1,other,at_home,...,2,3,3,3,5,5,8,9,9,24

In [86]:
df2["Age Group"] = pd.cut(
    df2["age"],
    bins=[0,20,35,100],
    labels=["Young","Adult","Senior"]
)

In [87]:
df2[["age", "Age Group"]]

     age Age Group
0     18     Young
1     17     Young
2     15     Young
3     15     Young
4     16     Young
..   ...       ...
390   20     Young
391   17     Young
392   21     Adult
393   18     Young
394   19     Young

[395 rows x 2 columns]

In [ ]:
#GroupBy and Aggregation

In [88]:
df2

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,goout,Dalc,Walc,health,absences,G1,G2,G3,Age after 5 years,Age Group
0,GP,F,18,U,GT3,A,4,4,at_home,teacher,...,4,1,1,3,6,5,6,6,23,Young
1,GP,F,17,U,GT3,T,1,1,at_home,other,...,3,1,1,3,4,5,5,6,22,Young
2,GP,F,15,U,LE3,T,1,1,at_home,other,...,2,2,3,3,10,7,8,10,20,Young
3,GP,F,15,U,GT3,T,4,2,health,services,...,2,1,1,5,2,15,14,15,20,Young
4,GP,F,16,U,GT3,T,3,3,other,other,...,2,1,2,5,4,6,10,10,21,Young
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
390,MS,M,20,U,LE3,A,2,2,services,services,...,4,4,5,4,11,9,9,9,25,Young
391,MS,M,17,U,LE3,T,3,1,services,services,...,5,3,4,2,3,14,16,16,22,Young
392,MS,M,21,R,GT3,T,1,1,other,other,...,3,3,3,3,3,10,8,7,26,Adult
393,MS,M,18,R,LE3,T,3,2,services,other,...,1,3,4,5,0,11,12,10,23,Young
394,MS,M,19,U,LE3,T,1,1,other,at_home,...,3,3,3,5,5,8,9,9,24,Young

In [93]:
df2.groupby("school")[["age"]].mean()

              age
school
GP      16.521490
MS      18.021739

In [94]:
df2.groupby("school")[["age"]].count()

        age
school
GP      349
MS       46

In [95]:
df2.groupby("school")[["age"]].max()

        age
school
GP       22
MS       21

In [96]:
df2.groupby("school")[["age"]].sum()

         age
school
GP      5766
MS       829

In [97]:
df2.groupby("school")[["age"]].median()

         age
school
GP      16.0
MS      18.0